targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: es
          fallback_strategy: base_locale
          input_directory: lib/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/i18n
          output_file_name: translations.g.dart
          output_format: single_file
          locale_handling: true
          flutter_integration: true
          translate_var: t
          enum_name: AppLocale
          translation_class_visibility: private
          timestamp: true
