name: neurolotto_admin
description: Sistema administrativo de venta de loteria
publish_to: "none"
version: 0.0.5+6

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  auto_route: ^7.8.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  supabase_flutter: ^1.10.24
  shared_preferences: ^2.2.2
  flutter_gen: ^5.3.1
  intl: ^0.18.0
  flutter_svg: ^2.0.7
  flex_color_scheme: ^7.3.1
  flutter_staggered_grid_view: ^0.7.0
  syncfusion_flutter_datagrid: ^23.2.4

  injectable: ^2.3.2
  get_it: ^7.6.4

  slang: ^3.25.0
  slang_flutter: ^3.25.0

  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1
  freezed: ^2.4.5
  slang_build_runner: ^3.25.0
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true
