import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

extension DarkTheme on ThemeData {
  ThemeData get darkTheme {
    final darkTheme = FlexThemeData.dark(
      colors: const FlexSchemeColor(
        primary: Color(0xff00296b),
        primaryContainer: Color(0xffa0c2ed),
        secondary: Color(0xffd26900),
        secondaryContainer: Color(0xffffd270),
        tertiary: Color(0xff5c5c95),
        tertiaryContainer: Color(0xffc8dbf8),
        appBarColor: Color(0xffc8dcf8),
        error: null,
      ),
      surfaceMode: FlexSurfaceMode.highBackgroundLowScaffold,
      blendLevel: 2,
      appBarStyle: FlexAppBarStyle.background,
      bottomAppBarElevation: 2.0,
      tabBarStyle: FlexTabBarStyle.forAppBar,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 8,
        useTextTheme: true,
        useM2StyleDividerInM3: true,
        adaptiveElevationShadowsBack: FlexAdaptive.all(),
        adaptiveAppBarScrollUnderOff: FlexAdaptive.excludeWebAndroidFuchsia(),
        defaultRadius: 6.0,
        adaptiveRadius: FlexAdaptive.excludeWebAndroidFuchsia(),
        defaultRadiusAdaptive: 12.0,
        elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
        elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
        outlinedButtonOutlineSchemeColor: SchemeColor.primary,
        toggleButtonsBorderSchemeColor: SchemeColor.primary,
        segmentedButtonSchemeColor: SchemeColor.primary,
        segmentedButtonBorderSchemeColor: SchemeColor.primary,
        unselectedToggleIsColored: true,
        sliderValueTinted: true,
        inputDecoratorSchemeColor: SchemeColor.onPrimary,
        inputDecoratorBackgroundAlpha: 22,
        inputDecoratorUnfocusedHasBorder: false,
        inputDecoratorFocusedBorderWidth: 1.0,
        inputDecoratorPrefixIconSchemeColor: SchemeColor.onPrimary,
        fabUseShape: true,
        fabRadius: 12.0,
        fabSchemeColor: SchemeColor.tertiary,
        cardRadius: 6.0,
        popupMenuRadius: 6.0,
        popupMenuElevation: 3.0,
        alignedDropdown: true,
        dialogRadius: 6.0,
        useInputDecoratorThemeInDialogs: true,
        datePickerHeaderBackgroundSchemeColor: SchemeColor.primary,
        snackBarBackgroundSchemeColor: SchemeColor.primary,
        snackBarActionSchemeColor: SchemeColor.onPrimary,
        appBarScrolledUnderElevation: 3.0,
        drawerRadius: 4.0,
        drawerElevation: 1.0,
        drawerIndicatorSchemeColor: SchemeColor.primary,
        bottomSheetRadius: 6.0,
        bottomSheetElevation: 2.0,
        bottomSheetModalElevation: 4.0,
        bottomNavigationBarMutedUnselectedLabel: false,
        bottomNavigationBarMutedUnselectedIcon: false,
        menuRadius: 6.0,
        menuElevation: 3.0,
        menuBarRadius: 0.0,
        menuBarElevation: 1.0,
        menuBarShadowColor: Color(0x00000000),
        navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
        navigationBarMutedUnselectedLabel: false,
        navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
        navigationBarMutedUnselectedIcon: false,
        navigationBarIndicatorSchemeColor: SchemeColor.primary,
        navigationBarIndicatorOpacity: 1.00,
        navigationBarIndicatorRadius: 6.0,
        navigationBarElevation: 1.0,
        navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
        navigationRailMutedUnselectedLabel: false,
        navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
        navigationRailMutedUnselectedIcon: false,
        navigationRailIndicatorSchemeColor: SchemeColor.primary,
        navigationRailIndicatorOpacity: 1.00,
        navigationRailIndicatorRadius: 6.0,
        navigationRailBackgroundSchemeColor: SchemeColor.surface,
      ),
      useMaterial3ErrorColors: true,
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: true,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    );

    return darkTheme;
  }
}
